name: C/C++ CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: installdeps
      run: sudo apt-get install -y libavcodec-dev libavformat-dev 
    - name: make
      working-directory: prores_encoder_plugin
      run: make
    - name: make install
      working-directory: prores_encoder_plugin
      run: make install
    - name: release
      uses: softprops/action-gh-release@v1
      working-directory: prores_encoder_plugin
      with files:  bin/**
