name: C/C++ CI

on: 
  push:
    branches: [ "main" ]
    tags:
      - "*"
  pull_request:
    branches: [ "main" ]
    

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: installdeps
      run: sudo apt-get install -y libavcodec-dev libavformat-dev 
    - name: make
      working-directory: prores_encoder_plugin
      run: make
    - name: make install
      working-directory: prores_encoder_plugin
      run: make install
    - name: make dist
      working-directory: prores_encoder_plugin
      run: make dist
    - name: Set Tag Name
      run: echo "TAG_NAME=$(echo $GITHUB_REF | sed 's/refs\/tags\///')" >> $GITHUB_ENV
    - name: Rename Binary with Tag Name
      run: mv prores_encoder_plugin/bin/release.zip "release-${{ env.TAG_NAME }}.zip"
    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files:  release-${{ env.TAG_NAME }}.zip
